FROM mariadb:11.4.8@sha256:bc474f00629f0123c10f9e1bca193a45d18af15a274cf0656acda64f1086c3b6

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y bash bash-completion nano vim-tiny
